import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { useAuth } from "@/services/useAuth";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div style={{ display: "flex", height: "100vh" }}>
          <nav
            style={{
              width: "200px",
              padding: "20px",
              // background: "#f4f4f4",
              borderRight: "1px solid #ddd",
            }}
          >
            <h2>contents TBD</h2>
            <ul className="ml-3">
              <li>
                <Link href="/timesheets-list">Timesheets</Link>
              </li>
              <li>
                <Link href="/auth-page">
                  {/* {userId ? (
                    <span>You are signed in</span>
                  ) : (
                    <span>Sign up</span>
                  )} */}
                </Link>
              </li>
              <li>
                <Link href="/tutorial">Tutorial</Link>
              </li>
              <li>
                <Link href="/dev-page">Dev Stuff</Link>
              </li>
            </ul>
          </nav>
          <main style={{ flex: 1, padding: "20px" }}>
            {children} {/* Renders the page content */}
          </main>
        </div>
      </body>
    </html>
  );
}
